package com.example.ronik.myticketproject1;

import android.content.Context;
import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteOpenHelper;
import android.util.Log;

import java.util.ArrayList;

public class MySQLiteOpenHelper extends SQLiteOpenHelper {

    public static final String TABLE_QUESTIONS_AND_ANSWERS = "questions_answers";
    public static final String COLUMN_ID_QUESTIONS = "_id";
    public static final String COLUMN_QUESTIONS = "questions";

    public static final String COLUMN_CORRECT_ANSWER = "correct_answer";
    public static final String COLUMN_WRONG_ANSWER0 = "wrong_answer0";
    public static final String COLUMN_WRONG_ANSWER1 = "wrong_answer1";
    public static final String COLUMN_WRONG_ANSWER2 = "wrong_answer2";

    public static final String DATABASE_NAME = "AlphaTriv.db";
    private static final int DATABASE_VERSION = 1;

    private static final String QUESTIONS_AND_ANSWERS_TABLE_CREATE =
            "CREATE TABLE " + TABLE_QUESTIONS_AND_ANSWERS +
                    " (" + COLUMN_ID_QUESTIONS +" INTEGER PRIMARY KEY AUTOINCREMENT, " +
                    COLUMN_QUESTIONS + " VARCHAR NOT NULL DEFAULT 'NOT_INIT_YET', " +
                    COLUMN_CORRECT_ANSWER +" VARCHAR NOT NULL DEFAULT 'NOT_INIT_YET', " +
                    COLUMN_WRONG_ANSWER0 +" VARCHAR NOT NULL DEFAULT 'NOT_INIT_YET', " +
                    COLUMN_WRONG_ANSWER1 +" VARCHAR NOT NULL DEFAULT 'NOT_INIT_YET', " +
                    COLUMN_WRONG_ANSWER2 +" VARCHAR NOT NULL DEFAULT 'NOT_INIT_YET' );";

    public MySQLiteOpenHelper(Context context) {
        super(context, DATABASE_NAME, null, DATABASE_VERSION);
    }

    @Override
    public void onCreate(SQLiteDatabase sqLiteDatabase) {
        sqLiteDatabase.execSQL(QUESTIONS_AND_ANSWERS_TABLE_CREATE);
        System.out.println("Hi");
    }

    @Override
    public void onUpgrade(SQLiteDatabase sqLiteDatabase, int oldVersion, int newVersion) {
        Log.w(MySQLiteOpenHelper.class.getName(),
                "Upgrading db from version " + oldVersion + " to " +
                        newVersion + ", which willdestroy all old data");
        sqLiteDatabase.execSQL("DROP TABLE IF EXISTS " + TABLE_QUESTIONS_AND_ANSWERS);
        onCreate(sqLiteDatabase);
    }
    //=======================================================================
    public void dropTable(SQLiteDatabase sqLiteDatabase , String tableName){
        sqLiteDatabase.execSQL("DROP TABLE IF EXISTS ''" + tableName + "''" );//+ TABLE_QUESTIONS_AND_ANSWERS
    }
    //========================================================================
    public void insertQuestionsAndAnswers(SQLiteDatabase sqLiteDatabase){
        sqLiteDatabase.execSQL("INSERT INTO " + TABLE_QUESTIONS_AND_ANSWERS+"("+COLUMN_QUESTIONS+","+COLUMN_CORRECT_ANSWER+","+COLUMN_WRONG_ANSWER0+","+COLUMN_WRONG_ANSWER1+","+COLUMN_WRONG_ANSWER2+","+ COLUMN_ID_QUESTIONS+") VALUES('What is the English translation for the name of the German automaker Volkswagen?','People’s car','Best Car','Quality Car','Folk`s car',1);");
        sqLiteDatabase.execSQL("INSERT INTO " + TABLE_QUESTIONS_AND_ANSWERS+"("+COLUMN_QUESTIONS+","+COLUMN_CORRECT_ANSWER+","+COLUMN_WRONG_ANSWER0+","+COLUMN_WRONG_ANSWER1+","+COLUMN_WRONG_ANSWER2+","+ COLUMN_ID_QUESTIONS+") VALUES('With twelve Oscar nominations and three wins, who is the most nominated male actor in Academy Awards history?','Jack Nicholson','Leonardo DiCaprio','Kianu Rivs','Christiane Bale',2);");
        sqLiteDatabase.execSQL("INSERT INTO " + TABLE_QUESTIONS_AND_ANSWERS+"("+COLUMN_QUESTIONS+","+COLUMN_CORRECT_ANSWER+","+COLUMN_WRONG_ANSWER0+","+COLUMN_WRONG_ANSWER1+","+COLUMN_WRONG_ANSWER2+","+ COLUMN_ID_QUESTIONS+") VALUES('Tenochtitlan, founded in 1324, is now known as what city?','Mexico City','Madrid','Costa Rica','Guatemala',3);");
        sqLiteDatabase.execSQL("INSERT INTO " + TABLE_QUESTIONS_AND_ANSWERS+"("+COLUMN_QUESTIONS+","+COLUMN_CORRECT_ANSWER+","+COLUMN_WRONG_ANSWER0+","+COLUMN_WRONG_ANSWER1+","+COLUMN_WRONG_ANSWER2+","+ COLUMN_ID_QUESTIONS+") VALUES('Tenochtitlan, founded in 1324, is now known as what city?','Mexico City','Madrid','Costa Rica','Guatemala',3);");
        sqLiteDatabase.execSQL("INSERT INTO " + TABLE_QUESTIONS_AND_ANSWERS+"("+COLUMN_QUESTIONS+","+COLUMN_CORRECT_ANSWER+","+COLUMN_WRONG_ANSWER0+","+COLUMN_WRONG_ANSWER1+","+COLUMN_WRONG_ANSWER2+","+ COLUMN_ID_QUESTIONS+") VALUES('Tenochtitlan, founded in 1324, is now known as what city?','Mexico City','Madrid','Costa Rica','Guatemala',3);");
        sqLiteDatabase.execSQL("INSERT INTO " + TABLE_QUESTIONS_AND_ANSWERS+"("+COLUMN_QUESTIONS+","+COLUMN_CORRECT_ANSWER+","+COLUMN_WRONG_ANSWER0+","+COLUMN_WRONG_ANSWER1+","+COLUMN_WRONG_ANSWER2+","+ COLUMN_ID_QUESTIONS+") VALUES('Tenochtitlan, founded in 1324, is now known as what city?','Mexico City','Madrid','Costa Rica','Guatemala',3);");
        sqLiteDatabase.execSQL("INSERT INTO " + TABLE_QUESTIONS_AND_ANSWERS+"("+COLUMN_QUESTIONS+","+COLUMN_CORRECT_ANSWER+","+COLUMN_WRONG_ANSWER0+","+COLUMN_WRONG_ANSWER1+","+COLUMN_WRONG_ANSWER2+","+ COLUMN_ID_QUESTIONS+") VALUES('Tenochtitlan, founded in 1324, is now known as what city?','Mexico City','Madrid','Costa Rica','Guatemala',3);");
        sqLiteDatabase.execSQL("INSERT INTO " + TABLE_QUESTIONS_AND_ANSWERS+"("+COLUMN_QUESTIONS+","+COLUMN_CORRECT_ANSWER+","+COLUMN_WRONG_ANSWER0+","+COLUMN_WRONG_ANSWER1+","+COLUMN_WRONG_ANSWER2+","+ COLUMN_ID_QUESTIONS+") VALUES('Tenochtitlan, founded in 1324, is now known as what city?','Mexico City','Madrid','Costa Rica','Guatemala',3);");
        sqLiteDatabase.execSQL("INSERT INTO " + TABLE_QUESTIONS_AND_ANSWERS+"("+COLUMN_QUESTIONS+","+COLUMN_CORRECT_ANSWER+","+COLUMN_WRONG_ANSWER0+","+COLUMN_WRONG_ANSWER1+","+COLUMN_WRONG_ANSWER2+","+ COLUMN_ID_QUESTIONS+") VALUES('Tenochtitlan, founded in 1324, is now known as what city?','Mexico City','Madrid','Costa Rica','Guatemala',3);");
        sqLiteDatabase.execSQL("INSERT INTO " + TABLE_QUESTIONS_AND_ANSWERS+"("+COLUMN_QUESTIONS+","+COLUMN_CORRECT_ANSWER+","+COLUMN_WRONG_ANSWER0+","+COLUMN_WRONG_ANSWER1+","+COLUMN_WRONG_ANSWER2+","+ COLUMN_ID_QUESTIONS+") VALUES('Tenochtitlan, founded in 1324, is now known as what city?','Mexico City','Madrid','Costa Rica','Guatemala',3);");
        sqLiteDatabase.execSQL("INSERT INTO " + TABLE_QUESTIONS_AND_ANSWERS+"("+COLUMN_QUESTIONS+","+COLUMN_CORRECT_ANSWER+","+COLUMN_WRONG_ANSWER0+","+COLUMN_WRONG_ANSWER1+","+COLUMN_WRONG_ANSWER2+","+ COLUMN_ID_QUESTIONS+") VALUES('Tenochtitlan, founded in 1324, is now known as what city?','Mexico City','Madrid','Costa Rica','Guatemala',3);");
        sqLiteDatabase.execSQL("INSERT INTO " + TABLE_QUESTIONS_AND_ANSWERS+"("+COLUMN_QUESTIONS+","+COLUMN_CORRECT_ANSWER+","+COLUMN_WRONG_ANSWER0+","+COLUMN_WRONG_ANSWER1+","+COLUMN_WRONG_ANSWER2+","+ COLUMN_ID_QUESTIONS+") VALUES('Tenochtitlan, founded in 1324, is now known as what city?','Mexico City','Madrid','Costa Rica','Guatemala',3);");
        sqLiteDatabase.execSQL("INSERT INTO " + TABLE_QUESTIONS_AND_ANSWERS+"("+COLUMN_QUESTIONS+","+COLUMN_CORRECT_ANSWER+","+COLUMN_WRONG_ANSWER0+","+COLUMN_WRONG_ANSWER1+","+COLUMN_WRONG_ANSWER2+","+ COLUMN_ID_QUESTIONS+") VALUES('Tenochtitlan, founded in 1324, is now known as what city?','Mexico City','Madrid','Costa Rica','Guatemala',3);");
        sqLiteDatabase.execSQL("INSERT INTO " + TABLE_QUESTIONS_AND_ANSWERS+"("+COLUMN_QUESTIONS+","+COLUMN_CORRECT_ANSWER+","+COLUMN_WRONG_ANSWER0+","+COLUMN_WRONG_ANSWER1+","+COLUMN_WRONG_ANSWER2+","+ COLUMN_ID_QUESTIONS+") VALUES('Tenochtitlan, founded in 1324, is now known as what city?','Mexico City','Madrid','Costa Rica','Guatemala',3);");
        sqLiteDatabase.execSQL("INSERT INTO " + TABLE_QUESTIONS_AND_ANSWERS+"("+COLUMN_QUESTIONS+","+COLUMN_CORRECT_ANSWER+","+COLUMN_WRONG_ANSWER0+","+COLUMN_WRONG_ANSWER1+","+COLUMN_WRONG_ANSWER2+","+ COLUMN_ID_QUESTIONS+") VALUES('Tenochtitlan, founded in 1324, is now known as what city?','Mexico City','Madrid','Costa Rica','Guatemala',3);");
        sqLiteDatabase.execSQL("INSERT INTO " + TABLE_QUESTIONS_AND_ANSWERS+"("+COLUMN_QUESTIONS+","+COLUMN_CORRECT_ANSWER+","+COLUMN_WRONG_ANSWER0+","+COLUMN_WRONG_ANSWER1+","+COLUMN_WRONG_ANSWER2+","+ COLUMN_ID_QUESTIONS+") VALUES('Tenochtitlan, founded in 1324, is now known as what city?','Mexico City','Madrid','Costa Rica','Guatemala',3);");
        sqLiteDatabase.execSQL("INSERT INTO " + TABLE_QUESTIONS_AND_ANSWERS+"("+COLUMN_QUESTIONS+","+COLUMN_CORRECT_ANSWER+","+COLUMN_WRONG_ANSWER0+","+COLUMN_WRONG_ANSWER1+","+COLUMN_WRONG_ANSWER2+","+ COLUMN_ID_QUESTIONS+") VALUES('Tenochtitlan, founded in 1324, is now known as what city?','Mexico City','Madrid','Costa Rica','Guatemala',3);");
        sqLiteDatabase.execSQL("INSERT INTO " + TABLE_QUESTIONS_AND_ANSWERS+"("+COLUMN_QUESTIONS+","+COLUMN_CORRECT_ANSWER+","+COLUMN_WRONG_ANSWER0+","+COLUMN_WRONG_ANSWER1+","+COLUMN_WRONG_ANSWER2+","+ COLUMN_ID_QUESTIONS+") VALUES('Tenochtitlan, founded in 1324, is now known as what city?','Mexico City','Madrid','Costa Rica','Guatemala',3);");
        sqLiteDatabase.execSQL("INSERT INTO " + TABLE_QUESTIONS_AND_ANSWERS+"("+COLUMN_QUESTIONS+","+COLUMN_CORRECT_ANSWER+","+COLUMN_WRONG_ANSWER0+","+COLUMN_WRONG_ANSWER1+","+COLUMN_WRONG_ANSWER2+","+ COLUMN_ID_QUESTIONS+") VALUES('Tenochtitlan, founded in 1324, is now known as what city?','Mexico City','Madrid','Costa Rica','Guatemala',3);");
        sqLiteDatabase.execSQL("INSERT INTO " + TABLE_QUESTIONS_AND_ANSWERS+"("+COLUMN_QUESTIONS+","+COLUMN_CORRECT_ANSWER+","+COLUMN_WRONG_ANSWER0+","+COLUMN_WRONG_ANSWER1+","+COLUMN_WRONG_ANSWER2+","+ COLUMN_ID_QUESTIONS+") VALUES('Tenochtitlan, founded in 1324, is now known as what city?','Mexico City','Madrid','Costa Rica','Guatemala',3);");
        sqLiteDatabase.execSQL("INSERT INTO " + TABLE_QUESTIONS_AND_ANSWERS+"("+COLUMN_QUESTIONS+","+COLUMN_CORRECT_ANSWER+","+COLUMN_WRONG_ANSWER0+","+COLUMN_WRONG_ANSWER1+","+COLUMN_WRONG_ANSWER2+","+ COLUMN_ID_QUESTIONS+") VALUES('Tenochtitlan, founded in 1324, is now known as what city?','Mexico City','Madrid','Costa Rica','Guatemala',3);");
        sqLiteDatabase.execSQL("INSERT INTO " + TABLE_QUESTIONS_AND_ANSWERS+"("+COLUMN_QUESTIONS+","+COLUMN_CORRECT_ANSWER+","+COLUMN_WRONG_ANSWER0+","+COLUMN_WRONG_ANSWER1+","+COLUMN_WRONG_ANSWER2+","+ COLUMN_ID_QUESTIONS+") VALUES('Tenochtitlan, founded in 1324, is now known as what city?','Mexico City','Madrid','Costa Rica','Guatemala',3);");

        sqLiteDatabase.execSQL("INSERT INTO " + TABLE_QUESTIONS_AND_ANSWERS+"("+COLUMN_QUESTIONS+","+COLUMN_CORRECT_ANSWER+","+COLUMN_WRONG_ANSWER0+","+COLUMN_WRONG_ANSWER1+","+COLUMN_WRONG_ANSWER2+","+ COLUMN_ID_QUESTIONS+") VALUES('Tenochtitlan, founded in 1324, is now known as what city?','Mexico City','Madrid','Costa Rica','Guatemala',3);");
        sqLiteDatabase.execSQL("INSERT INTO " + TABLE_QUESTIONS_AND_ANSWERS+"("+COLUMN_QUESTIONS+","+COLUMN_CORRECT_ANSWER+","+COLUMN_WRONG_ANSWER0+","+COLUMN_WRONG_ANSWER1+","+COLUMN_WRONG_ANSWER2+","+ COLUMN_ID_QUESTIONS+") VALUES('Tenochtitlan, founded in 1324, is now known as what city?','Mexico City','Madrid','Costa Rica','Guatemala',3);");
        sqLiteDatabase.execSQL("INSERT INTO " + TABLE_QUESTIONS_AND_ANSWERS+"("+COLUMN_QUESTIONS+","+COLUMN_CORRECT_ANSWER+","+COLUMN_WRONG_ANSWER0+","+COLUMN_WRONG_ANSWER1+","+COLUMN_WRONG_ANSWER2+","+ COLUMN_ID_QUESTIONS+") VALUES('Tenochtitlan, founded in 1324, is now known as what city?','Mexico City','Madrid','Costa Rica','Guatemala',3);");
        sqLiteDatabase.execSQL("INSERT INTO " + TABLE_QUESTIONS_AND_ANSWERS+"("+COLUMN_QUESTIONS+","+COLUMN_CORRECT_ANSWER+","+COLUMN_WRONG_ANSWER0+","+COLUMN_WRONG_ANSWER1+","+COLUMN_WRONG_ANSWER2+","+ COLUMN_ID_QUESTIONS+") VALUES('Tenochtitlan, founded in 1324, is now known as what city?','Mexico City','Madrid','Costa Rica','Guatemala',3);");
        sqLiteDatabase.execSQL("INSERT INTO " + TABLE_QUESTIONS_AND_ANSWERS+"("+COLUMN_QUESTIONS+","+COLUMN_CORRECT_ANSWER+","+COLUMN_WRONG_ANSWER0+","+COLUMN_WRONG_ANSWER1+","+COLUMN_WRONG_ANSWER2+","+ COLUMN_ID_QUESTIONS+") VALUES('Tenochtitlan, founded in 1324, is now known as what city?','Mexico City','Madrid','Costa Rica','Guatemala',3);");
        sqLiteDatabase.execSQL("INSERT INTO " + TABLE_QUESTIONS_AND_ANSWERS+"("+COLUMN_QUESTIONS+","+COLUMN_CORRECT_ANSWER+","+COLUMN_WRONG_ANSWER0+","+COLUMN_WRONG_ANSWER1+","+COLUMN_WRONG_ANSWER2+","+ COLUMN_ID_QUESTIONS+") VALUES('Tenochtitlan, founded in 1324, is now known as what city?','Mexico City','Madrid','Costa Rica','Guatemala',3);");
        sqLiteDatabase.execSQL("INSERT INTO " + TABLE_QUESTIONS_AND_ANSWERS+"("+COLUMN_QUESTIONS+","+COLUMN_CORRECT_ANSWER+","+COLUMN_WRONG_ANSWER0+","+COLUMN_WRONG_ANSWER1+","+COLUMN_WRONG_ANSWER2+","+ COLUMN_ID_QUESTIONS+") VALUES('Tenochtitlan, founded in 1324, is now known as what city?','Mexico City','Madrid','Costa Rica','Guatemala',3);");
        sqLiteDatabase.execSQL("INSERT INTO " + TABLE_QUESTIONS_AND_ANSWERS+"("+COLUMN_QUESTIONS+","+COLUMN_CORRECT_ANSWER+","+COLUMN_WRONG_ANSWER0+","+COLUMN_WRONG_ANSWER1+","+COLUMN_WRONG_ANSWER2+","+ COLUMN_ID_QUESTIONS+") VALUES('Tenochtitlan, founded in 1324, is now known as what city?','Mexico City','Madrid','Costa Rica','Guatemala',3);");
        sqLiteDatabase.execSQL("INSERT INTO " + TABLE_QUESTIONS_AND_ANSWERS+"("+COLUMN_QUESTIONS+","+COLUMN_CORRECT_ANSWER+","+COLUMN_WRONG_ANSWER0+","+COLUMN_WRONG_ANSWER1+","+COLUMN_WRONG_ANSWER2+","+ COLUMN_ID_QUESTIONS+") VALUES('Tenochtitlan, founded in 1324, is now known as what city?','Mexico City','Madrid','Costa Rica','Guatemala',3);");
        sqLiteDatabase.execSQL("INSERT INTO " + TABLE_QUESTIONS_AND_ANSWERS+"("+COLUMN_QUESTIONS+","+COLUMN_CORRECT_ANSWER+","+COLUMN_WRONG_ANSWER0+","+COLUMN_WRONG_ANSWER1+","+COLUMN_WRONG_ANSWER2+","+ COLUMN_ID_QUESTIONS+") VALUES('Tenochtitlan, founded in 1324, is now known as what city?','Mexico City','Madrid','Costa Rica','Guatemala',3);");
        sqLiteDatabase.execSQL("INSERT INTO " + TABLE_QUESTIONS_AND_ANSWERS+"("+COLUMN_QUESTIONS+","+COLUMN_CORRECT_ANSWER+","+COLUMN_WRONG_ANSWER0+","+COLUMN_WRONG_ANSWER1+","+COLUMN_WRONG_ANSWER2+","+ COLUMN_ID_QUESTIONS+") VALUES('Tenochtitlan, founded in 1324, is now known as what city?','Mexico City','Madrid','Costa Rica','Guatemala',3);");
        sqLiteDatabase.execSQL("INSERT INTO " + TABLE_QUESTIONS_AND_ANSWERS+"("+COLUMN_QUESTIONS+","+COLUMN_CORRECT_ANSWER+","+COLUMN_WRONG_ANSWER0+","+COLUMN_WRONG_ANSWER1+","+COLUMN_WRONG_ANSWER2+","+ COLUMN_ID_QUESTIONS+") VALUES('Tenochtitlan, founded in 1324, is now known as what city?','Mexico City','Madrid','Costa Rica','Guatemala',3);");
        sqLiteDatabase.execSQL("INSERT INTO " + TABLE_QUESTIONS_AND_ANSWERS+"("+COLUMN_QUESTIONS+","+COLUMN_CORRECT_ANSWER+","+COLUMN_WRONG_ANSWER0+","+COLUMN_WRONG_ANSWER1+","+COLUMN_WRONG_ANSWER2+","+ COLUMN_ID_QUESTIONS+") VALUES('Tenochtitlan, founded in 1324, is now known as what city?','Mexico City','Madrid','Costa Rica','Guatemala',3);");
        sqLiteDatabase.execSQL("INSERT INTO " + TABLE_QUESTIONS_AND_ANSWERS+"("+COLUMN_QUESTIONS+","+COLUMN_CORRECT_ANSWER+","+COLUMN_WRONG_ANSWER0+","+COLUMN_WRONG_ANSWER1+","+COLUMN_WRONG_ANSWER2+","+ COLUMN_ID_QUESTIONS+") VALUES('Tenochtitlan, founded in 1324, is now known as what city?','Mexico City','Madrid','Costa Rica','Guatemala',3);");
        sqLiteDatabase.execSQL("INSERT INTO " + TABLE_QUESTIONS_AND_ANSWERS+"("+COLUMN_QUESTIONS+","+COLUMN_CORRECT_ANSWER+","+COLUMN_WRONG_ANSWER0+","+COLUMN_WRONG_ANSWER1+","+COLUMN_WRONG_ANSWER2+","+ COLUMN_ID_QUESTIONS+") VALUES('Tenochtitlan, founded in 1324, is now known as what city?','Mexico City','Madrid','Costa Rica','Guatemala',3);");
        sqLiteDatabase.execSQL("INSERT INTO " + TABLE_QUESTIONS_AND_ANSWERS+"("+COLUMN_QUESTIONS+","+COLUMN_CORRECT_ANSWER+","+COLUMN_WRONG_ANSWER0+","+COLUMN_WRONG_ANSWER1+","+COLUMN_WRONG_ANSWER2+","+ COLUMN_ID_QUESTIONS+") VALUES('Tenochtitlan, founded in 1324, is now known as what city?','Mexico City','Madrid','Costa Rica','Guatemala',3);");
        sqLiteDatabase.execSQL("INSERT INTO " + TABLE_QUESTIONS_AND_ANSWERS+"("+COLUMN_QUESTIONS+","+COLUMN_CORRECT_ANSWER+","+COLUMN_WRONG_ANSWER0+","+COLUMN_WRONG_ANSWER1+","+COLUMN_WRONG_ANSWER2+","+ COLUMN_ID_QUESTIONS+") VALUES('Tenochtitlan, founded in 1324, is now known as what city?','Mexico City','Madrid','Costa Rica','Guatemala',3);");
        sqLiteDatabase.execSQL("INSERT INTO " + TABLE_QUESTIONS_AND_ANSWERS+"("+COLUMN_QUESTIONS+","+COLUMN_CORRECT_ANSWER+","+COLUMN_WRONG_ANSWER0+","+COLUMN_WRONG_ANSWER1+","+COLUMN_WRONG_ANSWER2+","+ COLUMN_ID_QUESTIONS+") VALUES('Tenochtitlan, founded in 1324, is now known as what city?','Mexico City','Madrid','Costa Rica','Guatemala',3);");
        sqLiteDatabase.execSQL("INSERT INTO " + TABLE_QUESTIONS_AND_ANSWERS+"("+COLUMN_QUESTIONS+","+COLUMN_CORRECT_ANSWER+","+COLUMN_WRONG_ANSWER0+","+COLUMN_WRONG_ANSWER1+","+COLUMN_WRONG_ANSWER2+","+ COLUMN_ID_QUESTIONS+") VALUES('Tenochtitlan, founded in 1324, is now known as what city?','Mexico City','Madrid','Costa Rica','Guatemala',3);");
        sqLiteDatabase.execSQL("INSERT INTO " + TABLE_QUESTIONS_AND_ANSWERS+"("+COLUMN_QUESTIONS+","+COLUMN_CORRECT_ANSWER+","+COLUMN_WRONG_ANSWER0+","+COLUMN_WRONG_ANSWER1+","+COLUMN_WRONG_ANSWER2+","+ COLUMN_ID_QUESTIONS+") VALUES('Tenochtitlan, founded in 1324, is now known as what city?','Mexico City','Madrid','Costa Rica','Guatemala',3);");

        sqLiteDatabase.execSQL("INSERT INTO " + TABLE_QUESTIONS_AND_ANSWERS+"("+COLUMN_QUESTIONS+","+COLUMN_CORRECT_ANSWER+","+COLUMN_WRONG_ANSWER0+","+COLUMN_WRONG_ANSWER1+","+COLUMN_WRONG_ANSWER2+","+ COLUMN_ID_QUESTIONS+") VALUES('Tenochtitlan, founded in 1324, is now known as what city?','Mexico City','Madrid','Costa Rica','Guatemala',3);");
        sqLiteDatabase.execSQL("INSERT INTO " + TABLE_QUESTIONS_AND_ANSWERS+"("+COLUMN_QUESTIONS+","+COLUMN_CORRECT_ANSWER+","+COLUMN_WRONG_ANSWER0+","+COLUMN_WRONG_ANSWER1+","+COLUMN_WRONG_ANSWER2+","+ COLUMN_ID_QUESTIONS+") VALUES('Tenochtitlan, founded in 1324, is now known as what city?','Mexico City','Madrid','Costa Rica','Guatemala',3);");
        sqLiteDatabase.execSQL("INSERT INTO " + TABLE_QUESTIONS_AND_ANSWERS+"("+COLUMN_QUESTIONS+","+COLUMN_CORRECT_ANSWER+","+COLUMN_WRONG_ANSWER0+","+COLUMN_WRONG_ANSWER1+","+COLUMN_WRONG_ANSWER2+","+ COLUMN_ID_QUESTIONS+") VALUES('Tenochtitlan, founded in 1324, is now known as what city?','Mexico City','Madrid','Costa Rica','Guatemala',3);");
        sqLiteDatabase.execSQL("INSERT INTO " + TABLE_QUESTIONS_AND_ANSWERS+"("+COLUMN_QUESTIONS+","+COLUMN_CORRECT_ANSWER+","+COLUMN_WRONG_ANSWER0+","+COLUMN_WRONG_ANSWER1+","+COLUMN_WRONG_ANSWER2+","+ COLUMN_ID_QUESTIONS+") VALUES('Tenochtitlan, founded in 1324, is now known as what city?','Mexico City','Madrid','Costa Rica','Guatemala',3);");
        sqLiteDatabase.execSQL("INSERT INTO " + TABLE_QUESTIONS_AND_ANSWERS+"("+COLUMN_QUESTIONS+","+COLUMN_CORRECT_ANSWER+","+COLUMN_WRONG_ANSWER0+","+COLUMN_WRONG_ANSWER1+","+COLUMN_WRONG_ANSWER2+","+ COLUMN_ID_QUESTIONS+") VALUES('Tenochtitlan, founded in 1324, is now known as what city?','Mexico City','Madrid','Costa Rica','Guatemala',3);");
        sqLiteDatabase.execSQL("INSERT INTO " + TABLE_QUESTIONS_AND_ANSWERS+"("+COLUMN_QUESTIONS+","+COLUMN_CORRECT_ANSWER+","+COLUMN_WRONG_ANSWER0+","+COLUMN_WRONG_ANSWER1+","+COLUMN_WRONG_ANSWER2+","+ COLUMN_ID_QUESTIONS+") VALUES('Tenochtitlan, founded in 1324, is now known as what city?','Mexico City','Madrid','Costa Rica','Guatemala',3);");
        sqLiteDatabase.execSQL("INSERT INTO " + TABLE_QUESTIONS_AND_ANSWERS+"("+COLUMN_QUESTIONS+","+COLUMN_CORRECT_ANSWER+","+COLUMN_WRONG_ANSWER0+","+COLUMN_WRONG_ANSWER1+","+COLUMN_WRONG_ANSWER2+","+ COLUMN_ID_QUESTIONS+") VALUES('Tenochtitlan, founded in 1324, is now known as what city?','Mexico City','Madrid','Costa Rica','Guatemala',3);");
        sqLiteDatabase.execSQL("INSERT INTO " + TABLE_QUESTIONS_AND_ANSWERS+"("+COLUMN_QUESTIONS+","+COLUMN_CORRECT_ANSWER+","+COLUMN_WRONG_ANSWER0+","+COLUMN_WRONG_ANSWER1+","+COLUMN_WRONG_ANSWER2+","+ COLUMN_ID_QUESTIONS+") VALUES('Tenochtitlan, founded in 1324, is now known as what city?','Mexico City','Madrid','Costa Rica','Guatemala',3);");
        sqLiteDatabase.execSQL("INSERT INTO " + TABLE_QUESTIONS_AND_ANSWERS+"("+COLUMN_QUESTIONS+","+COLUMN_CORRECT_ANSWER+","+COLUMN_WRONG_ANSWER0+","+COLUMN_WRONG_ANSWER1+","+COLUMN_WRONG_ANSWER2+","+ COLUMN_ID_QUESTIONS+") VALUES('Tenochtitlan, founded in 1324, is now known as what city?','Mexico City','Madrid','Costa Rica','Guatemala',3);");
        sqLiteDatabase.execSQL("INSERT INTO " + TABLE_QUESTIONS_AND_ANSWERS+"("+COLUMN_QUESTIONS+","+COLUMN_CORRECT_ANSWER+","+COLUMN_WRONG_ANSWER0+","+COLUMN_WRONG_ANSWER1+","+COLUMN_WRONG_ANSWER2+","+ COLUMN_ID_QUESTIONS+") VALUES('Tenochtitlan, founded in 1324, is now known as what city?','Mexico City','Madrid','Costa Rica','Guatemala',3);");
        sqLiteDatabase.execSQL("INSERT INTO " + TABLE_QUESTIONS_AND_ANSWERS+"("+COLUMN_QUESTIONS+","+COLUMN_CORRECT_ANSWER+","+COLUMN_WRONG_ANSWER0+","+COLUMN_WRONG_ANSWER1+","+COLUMN_WRONG_ANSWER2+","+ COLUMN_ID_QUESTIONS+") VALUES('Tenochtitlan, founded in 1324, is now known as what city?','Mexico City','Madrid','Costa Rica','Guatemala',3);");
        sqLiteDatabase.execSQL("INSERT INTO " + TABLE_QUESTIONS_AND_ANSWERS+"("+COLUMN_QUESTIONS+","+COLUMN_CORRECT_ANSWER+","+COLUMN_WRONG_ANSWER0+","+COLUMN_WRONG_ANSWER1+","+COLUMN_WRONG_ANSWER2+","+ COLUMN_ID_QUESTIONS+") VALUES('Tenochtitlan, founded in 1324, is now known as what city?','Mexico City','Madrid','Costa Rica','Guatemala',3);");
        sqLiteDatabase.execSQL("INSERT INTO " + TABLE_QUESTIONS_AND_ANSWERS+"("+COLUMN_QUESTIONS+","+COLUMN_CORRECT_ANSWER+","+COLUMN_WRONG_ANSWER0+","+COLUMN_WRONG_ANSWER1+","+COLUMN_WRONG_ANSWER2+","+ COLUMN_ID_QUESTIONS+") VALUES('Tenochtitlan, founded in 1324, is now known as what city?','Mexico City','Madrid','Costa Rica','Guatemala',3);");
        sqLiteDatabase.execSQL("INSERT INTO " + TABLE_QUESTIONS_AND_ANSWERS+"("+COLUMN_QUESTIONS+","+COLUMN_CORRECT_ANSWER+","+COLUMN_WRONG_ANSWER0+","+COLUMN_WRONG_ANSWER1+","+COLUMN_WRONG_ANSWER2+","+ COLUMN_ID_QUESTIONS+") VALUES('Tenochtitlan, founded in 1324, is now known as what city?','Mexico City','Madrid','Costa Rica','Guatemala',3);");
        sqLiteDatabase.execSQL("INSERT INTO " + TABLE_QUESTIONS_AND_ANSWERS+"("+COLUMN_QUESTIONS+","+COLUMN_CORRECT_ANSWER+","+COLUMN_WRONG_ANSWER0+","+COLUMN_WRONG_ANSWER1+","+COLUMN_WRONG_ANSWER2+","+ COLUMN_ID_QUESTIONS+") VALUES('Tenochtitlan, founded in 1324, is now known as what city?','Mexico City','Madrid','Costa Rica','Guatemala',3);");
        sqLiteDatabase.execSQL("INSERT INTO " + TABLE_QUESTIONS_AND_ANSWERS+"("+COLUMN_QUESTIONS+","+COLUMN_CORRECT_ANSWER+","+COLUMN_WRONG_ANSWER0+","+COLUMN_WRONG_ANSWER1+","+COLUMN_WRONG_ANSWER2+","+ COLUMN_ID_QUESTIONS+") VALUES('Tenochtitlan, founded in 1324, is now known as what city?','Mexico City','Madrid','Costa Rica','Guatemala',3);");
        sqLiteDatabase.execSQL("INSERT INTO " + TABLE_QUESTIONS_AND_ANSWERS+"("+COLUMN_QUESTIONS+","+COLUMN_CORRECT_ANSWER+","+COLUMN_WRONG_ANSWER0+","+COLUMN_WRONG_ANSWER1+","+COLUMN_WRONG_ANSWER2+","+ COLUMN_ID_QUESTIONS+") VALUES('Tenochtitlan, founded in 1324, is now known as what city?','Mexico City','Madrid','Costa Rica','Guatemala',3);");
        sqLiteDatabase.execSQL("INSERT INTO " + TABLE_QUESTIONS_AND_ANSWERS+"("+COLUMN_QUESTIONS+","+COLUMN_CORRECT_ANSWER+","+COLUMN_WRONG_ANSWER0+","+COLUMN_WRONG_ANSWER1+","+COLUMN_WRONG_ANSWER2+","+ COLUMN_ID_QUESTIONS+") VALUES('Tenochtitlan, founded in 1324, is now known as what city?','Mexico City','Madrid','Costa Rica','Guatemala',3);");
        sqLiteDatabase.execSQL("INSERT INTO " + TABLE_QUESTIONS_AND_ANSWERS+"("+COLUMN_QUESTIONS+","+COLUMN_CORRECT_ANSWER+","+COLUMN_WRONG_ANSWER0+","+COLUMN_WRONG_ANSWER1+","+COLUMN_WRONG_ANSWER2+","+ COLUMN_ID_QUESTIONS+") VALUES('Tenochtitlan, founded in 1324, is now known as what city?','Mexico City','Madrid','Costa Rica','Guatemala',3);");
        sqLiteDatabase.execSQL("INSERT INTO " + TABLE_QUESTIONS_AND_ANSWERS+"("+COLUMN_QUESTIONS+","+COLUMN_CORRECT_ANSWER+","+COLUMN_WRONG_ANSWER0+","+COLUMN_WRONG_ANSWER1+","+COLUMN_WRONG_ANSWER2+","+ COLUMN_ID_QUESTIONS+") VALUES('Tenochtitlan, founded in 1324, is now known as what city?','Mexico City','Madrid','Costa Rica','Guatemala',3);");

        sqLiteDatabase.execSQL("INSERT INTO " + TABLE_QUESTIONS_AND_ANSWERS+"("+COLUMN_QUESTIONS+","+COLUMN_CORRECT_ANSWER+","+COLUMN_WRONG_ANSWER0+","+COLUMN_WRONG_ANSWER1+","+COLUMN_WRONG_ANSWER2+","+ COLUMN_ID_QUESTIONS+") VALUES('Tenochtitlan, founded in 1324, is now known as what city?','Mexico City','Madrid','Costa Rica','Guatemala',3);");
        sqLiteDatabase.execSQL("INSERT INTO " + TABLE_QUESTIONS_AND_ANSWERS+"("+COLUMN_QUESTIONS+","+COLUMN_CORRECT_ANSWER+","+COLUMN_WRONG_ANSWER0+","+COLUMN_WRONG_ANSWER1+","+COLUMN_WRONG_ANSWER2+","+ COLUMN_ID_QUESTIONS+") VALUES('Tenochtitlan, founded in 1324, is now known as what city?','Mexico City','Madrid','Costa Rica','Guatemala',3);");
        sqLiteDatabase.execSQL("INSERT INTO " + TABLE_QUESTIONS_AND_ANSWERS+"("+COLUMN_QUESTIONS+","+COLUMN_CORRECT_ANSWER+","+COLUMN_WRONG_ANSWER0+","+COLUMN_WRONG_ANSWER1+","+COLUMN_WRONG_ANSWER2+","+ COLUMN_ID_QUESTIONS+") VALUES('Tenochtitlan, founded in 1324, is now known as what city?','Mexico City','Madrid','Costa Rica','Guatemala',3);");
        sqLiteDatabase.execSQL("INSERT INTO " + TABLE_QUESTIONS_AND_ANSWERS+"("+COLUMN_QUESTIONS+","+COLUMN_CORRECT_ANSWER+","+COLUMN_WRONG_ANSWER0+","+COLUMN_WRONG_ANSWER1+","+COLUMN_WRONG_ANSWER2+","+ COLUMN_ID_QUESTIONS+") VALUES('Tenochtitlan, founded in 1324, is now known as what city?','Mexico City','Madrid','Costa Rica','Guatemala',3);");
        sqLiteDatabase.execSQL("INSERT INTO " + TABLE_QUESTIONS_AND_ANSWERS+"("+COLUMN_QUESTIONS+","+COLUMN_CORRECT_ANSWER+","+COLUMN_WRONG_ANSWER0+","+COLUMN_WRONG_ANSWER1+","+COLUMN_WRONG_ANSWER2+","+ COLUMN_ID_QUESTIONS+") VALUES('Tenochtitlan, founded in 1324, is now known as what city?','Mexico City','Madrid','Costa Rica','Guatemala',3);");
        sqLiteDatabase.execSQL("INSERT INTO " + TABLE_QUESTIONS_AND_ANSWERS+"("+COLUMN_QUESTIONS+","+COLUMN_CORRECT_ANSWER+","+COLUMN_WRONG_ANSWER0+","+COLUMN_WRONG_ANSWER1+","+COLUMN_WRONG_ANSWER2+","+ COLUMN_ID_QUESTIONS+") VALUES('Tenochtitlan, founded in 1324, is now known as what city?','Mexico City','Madrid','Costa Rica','Guatemala',3);");
        sqLiteDatabase.execSQL("INSERT INTO " + TABLE_QUESTIONS_AND_ANSWERS+"("+COLUMN_QUESTIONS+","+COLUMN_CORRECT_ANSWER+","+COLUMN_WRONG_ANSWER0+","+COLUMN_WRONG_ANSWER1+","+COLUMN_WRONG_ANSWER2+","+ COLUMN_ID_QUESTIONS+") VALUES('Tenochtitlan, founded in 1324, is now known as what city?','Mexico City','Madrid','Costa Rica','Guatemala',3);");
        sqLiteDatabase.execSQL("INSERT INTO " + TABLE_QUESTIONS_AND_ANSWERS+"("+COLUMN_QUESTIONS+","+COLUMN_CORRECT_ANSWER+","+COLUMN_WRONG_ANSWER0+","+COLUMN_WRONG_ANSWER1+","+COLUMN_WRONG_ANSWER2+","+ COLUMN_ID_QUESTIONS+") VALUES('Tenochtitlan, founded in 1324, is now known as what city?','Mexico City','Madrid','Costa Rica','Guatemala',3);");
        sqLiteDatabase.execSQL("INSERT INTO " + TABLE_QUESTIONS_AND_ANSWERS+"("+COLUMN_QUESTIONS+","+COLUMN_CORRECT_ANSWER+","+COLUMN_WRONG_ANSWER0+","+COLUMN_WRONG_ANSWER1+","+COLUMN_WRONG_ANSWER2+","+ COLUMN_ID_QUESTIONS+") VALUES('Tenochtitlan, founded in 1324, is now known as what city?','Mexico City','Madrid','Costa Rica','Guatemala',3);");
        sqLiteDatabase.execSQL("INSERT INTO " + TABLE_QUESTIONS_AND_ANSWERS+"("+COLUMN_QUESTIONS+","+COLUMN_CORRECT_ANSWER+","+COLUMN_WRONG_ANSWER0+","+COLUMN_WRONG_ANSWER1+","+COLUMN_WRONG_ANSWER2+","+ COLUMN_ID_QUESTIONS+") VALUES('Tenochtitlan, founded in 1324, is now known as what city?','Mexico City','Madrid','Costa Rica','Guatemala',3);");
        sqLiteDatabase.execSQL("INSERT INTO " + TABLE_QUESTIONS_AND_ANSWERS+"("+COLUMN_QUESTIONS+","+COLUMN_CORRECT_ANSWER+","+COLUMN_WRONG_ANSWER0+","+COLUMN_WRONG_ANSWER1+","+COLUMN_WRONG_ANSWER2+","+ COLUMN_ID_QUESTIONS+") VALUES('Tenochtitlan, founded in 1324, is now known as what city?','Mexico City','Madrid','Costa Rica','Guatemala',3);");
        sqLiteDatabase.execSQL("INSERT INTO " + TABLE_QUESTIONS_AND_ANSWERS+"("+COLUMN_QUESTIONS+","+COLUMN_CORRECT_ANSWER+","+COLUMN_WRONG_ANSWER0+","+COLUMN_WRONG_ANSWER1+","+COLUMN_WRONG_ANSWER2+","+ COLUMN_ID_QUESTIONS+") VALUES('Tenochtitlan, founded in 1324, is now known as what city?','Mexico City','Madrid','Costa Rica','Guatemala',3);");
        sqLiteDatabase.execSQL("INSERT INTO " + TABLE_QUESTIONS_AND_ANSWERS+"("+COLUMN_QUESTIONS+","+COLUMN_CORRECT_ANSWER+","+COLUMN_WRONG_ANSWER0+","+COLUMN_WRONG_ANSWER1+","+COLUMN_WRONG_ANSWER2+","+ COLUMN_ID_QUESTIONS+") VALUES('Tenochtitlan, founded in 1324, is now known as what city?','Mexico City','Madrid','Costa Rica','Guatemala',3);");
        sqLiteDatabase.execSQL("INSERT INTO " + TABLE_QUESTIONS_AND_ANSWERS+"("+COLUMN_QUESTIONS+","+COLUMN_CORRECT_ANSWER+","+COLUMN_WRONG_ANSWER0+","+COLUMN_WRONG_ANSWER1+","+COLUMN_WRONG_ANSWER2+","+ COLUMN_ID_QUESTIONS+") VALUES('Tenochtitlan, founded in 1324, is now known as what city?','Mexico City','Madrid','Costa Rica','Guatemala',3);");
        sqLiteDatabase.execSQL("INSERT INTO " + TABLE_QUESTIONS_AND_ANSWERS+"("+COLUMN_QUESTIONS+","+COLUMN_CORRECT_ANSWER+","+COLUMN_WRONG_ANSWER0+","+COLUMN_WRONG_ANSWER1+","+COLUMN_WRONG_ANSWER2+","+ COLUMN_ID_QUESTIONS+") VALUES('Tenochtitlan, founded in 1324, is now known as what city?','Mexico City','Madrid','Costa Rica','Guatemala',3);");
        sqLiteDatabase.execSQL("INSERT INTO " + TABLE_QUESTIONS_AND_ANSWERS+"("+COLUMN_QUESTIONS+","+COLUMN_CORRECT_ANSWER+","+COLUMN_WRONG_ANSWER0+","+COLUMN_WRONG_ANSWER1+","+COLUMN_WRONG_ANSWER2+","+ COLUMN_ID_QUESTIONS+") VALUES('Tenochtitlan, founded in 1324, is now known as what city?','Mexico City','Madrid','Costa Rica','Guatemala',3);");
        sqLiteDatabase.execSQL("INSERT INTO " + TABLE_QUESTIONS_AND_ANSWERS+"("+COLUMN_QUESTIONS+","+COLUMN_CORRECT_ANSWER+","+COLUMN_WRONG_ANSWER0+","+COLUMN_WRONG_ANSWER1+","+COLUMN_WRONG_ANSWER2+","+ COLUMN_ID_QUESTIONS+") VALUES('Tenochtitlan, founded in 1324, is now known as what city?','Mexico City','Madrid','Costa Rica','Guatemala',3);");
        sqLiteDatabase.execSQL("INSERT INTO " + TABLE_QUESTIONS_AND_ANSWERS+"("+COLUMN_QUESTIONS+","+COLUMN_CORRECT_ANSWER+","+COLUMN_WRONG_ANSWER0+","+COLUMN_WRONG_ANSWER1+","+COLUMN_WRONG_ANSWER2+","+ COLUMN_ID_QUESTIONS+") VALUES('Tenochtitlan, founded in 1324, is now known as what city?','Mexico City','Madrid','Costa Rica','Guatemala',3);");
        sqLiteDatabase.execSQL("INSERT INTO " + TABLE_QUESTIONS_AND_ANSWERS+"("+COLUMN_QUESTIONS+","+COLUMN_CORRECT_ANSWER+","+COLUMN_WRONG_ANSWER0+","+COLUMN_WRONG_ANSWER1+","+COLUMN_WRONG_ANSWER2+","+ COLUMN_ID_QUESTIONS+") VALUES('Tenochtitlan, founded in 1324, is now known as what city?','Mexico City','Madrid','Costa Rica','Guatemala',3);");
        sqLiteDatabase.execSQL("INSERT INTO " + TABLE_QUESTIONS_AND_ANSWERS+"("+COLUMN_QUESTIONS+","+COLUMN_CORRECT_ANSWER+","+COLUMN_WRONG_ANSWER0+","+COLUMN_WRONG_ANSWER1+","+COLUMN_WRONG_ANSWER2+","+ COLUMN_ID_QUESTIONS+") VALUES('Tenochtitlan, founded in 1324, is now known as what city?','Mexico City','Madrid','Costa Rica','Guatemala',3);");

        sqLiteDatabase.execSQL("INSERT INTO " + TABLE_QUESTIONS_AND_ANSWERS+"("+COLUMN_QUESTIONS+","+COLUMN_CORRECT_ANSWER+","+COLUMN_WRONG_ANSWER0+","+COLUMN_WRONG_ANSWER1+","+COLUMN_WRONG_ANSWER2+","+ COLUMN_ID_QUESTIONS+") VALUES('Tenochtitlan, founded in 1324, is now known as what city?','Mexico City','Madrid','Costa Rica','Guatemala',3);");
        sqLiteDatabase.execSQL("INSERT INTO " + TABLE_QUESTIONS_AND_ANSWERS+"("+COLUMN_QUESTIONS+","+COLUMN_CORRECT_ANSWER+","+COLUMN_WRONG_ANSWER0+","+COLUMN_WRONG_ANSWER1+","+COLUMN_WRONG_ANSWER2+","+ COLUMN_ID_QUESTIONS+") VALUES('Tenochtitlan, founded in 1324, is now known as what city?','Mexico City','Madrid','Costa Rica','Guatemala',3);");
        sqLiteDatabase.execSQL("INSERT INTO " + TABLE_QUESTIONS_AND_ANSWERS+"("+COLUMN_QUESTIONS+","+COLUMN_CORRECT_ANSWER+","+COLUMN_WRONG_ANSWER0+","+COLUMN_WRONG_ANSWER1+","+COLUMN_WRONG_ANSWER2+","+ COLUMN_ID_QUESTIONS+") VALUES('Tenochtitlan, founded in 1324, is now known as what city?','Mexico City','Madrid','Costa Rica','Guatemala',3);");
        sqLiteDatabase.execSQL("INSERT INTO " + TABLE_QUESTIONS_AND_ANSWERS+"("+COLUMN_QUESTIONS+","+COLUMN_CORRECT_ANSWER+","+COLUMN_WRONG_ANSWER0+","+COLUMN_WRONG_ANSWER1+","+COLUMN_WRONG_ANSWER2+","+ COLUMN_ID_QUESTIONS+") VALUES('Tenochtitlan, founded in 1324, is now known as what city?','Mexico City','Madrid','Costa Rica','Guatemala',3);");
        sqLiteDatabase.execSQL("INSERT INTO " + TABLE_QUESTIONS_AND_ANSWERS+"("+COLUMN_QUESTIONS+","+COLUMN_CORRECT_ANSWER+","+COLUMN_WRONG_ANSWER0+","+COLUMN_WRONG_ANSWER1+","+COLUMN_WRONG_ANSWER2+","+ COLUMN_ID_QUESTIONS+") VALUES('Tenochtitlan, founded in 1324, is now known as what city?','Mexico City','Madrid','Costa Rica','Guatemala',3);");
        sqLiteDatabase.execSQL("INSERT INTO " + TABLE_QUESTIONS_AND_ANSWERS+"("+COLUMN_QUESTIONS+","+COLUMN_CORRECT_ANSWER+","+COLUMN_WRONG_ANSWER0+","+COLUMN_WRONG_ANSWER1+","+COLUMN_WRONG_ANSWER2+","+ COLUMN_ID_QUESTIONS+") VALUES('Tenochtitlan, founded in 1324, is now known as what city?','Mexico City','Madrid','Costa Rica','Guatemala',3);");
        sqLiteDatabase.execSQL("INSERT INTO " + TABLE_QUESTIONS_AND_ANSWERS+"("+COLUMN_QUESTIONS+","+COLUMN_CORRECT_ANSWER+","+COLUMN_WRONG_ANSWER0+","+COLUMN_WRONG_ANSWER1+","+COLUMN_WRONG_ANSWER2+","+ COLUMN_ID_QUESTIONS+") VALUES('Tenochtitlan, founded in 1324, is now known as what city?','Mexico City','Madrid','Costa Rica','Guatemala',3);");
        sqLiteDatabase.execSQL("INSERT INTO " + TABLE_QUESTIONS_AND_ANSWERS+"("+COLUMN_QUESTIONS+","+COLUMN_CORRECT_ANSWER+","+COLUMN_WRONG_ANSWER0+","+COLUMN_WRONG_ANSWER1+","+COLUMN_WRONG_ANSWER2+","+ COLUMN_ID_QUESTIONS+") VALUES('Tenochtitlan, founded in 1324, is now known as what city?','Mexico City','Madrid','Costa Rica','Guatemala',3);");
        sqLiteDatabase.execSQL("INSERT INTO " + TABLE_QUESTIONS_AND_ANSWERS+"("+COLUMN_QUESTIONS+","+COLUMN_CORRECT_ANSWER+","+COLUMN_WRONG_ANSWER0+","+COLUMN_WRONG_ANSWER1+","+COLUMN_WRONG_ANSWER2+","+ COLUMN_ID_QUESTIONS+") VALUES('Tenochtitlan, founded in 1324, is now known as what city?','Mexico City','Madrid','Costa Rica','Guatemala',3);");
        sqLiteDatabase.execSQL("INSERT INTO " + TABLE_QUESTIONS_AND_ANSWERS+"("+COLUMN_QUESTIONS+","+COLUMN_CORRECT_ANSWER+","+COLUMN_WRONG_ANSWER0+","+COLUMN_WRONG_ANSWER1+","+COLUMN_WRONG_ANSWER2+","+ COLUMN_ID_QUESTIONS+") VALUES('Tenochtitlan, founded in 1324, is now known as what city?','Mexico City','Madrid','Costa Rica','Guatemala',3);");
        sqLiteDatabase.execSQL("INSERT INTO " + TABLE_QUESTIONS_AND_ANSWERS+"("+COLUMN_QUESTIONS+","+COLUMN_CORRECT_ANSWER+","+COLUMN_WRONG_ANSWER0+","+COLUMN_WRONG_ANSWER1+","+COLUMN_WRONG_ANSWER2+","+ COLUMN_ID_QUESTIONS+") VALUES('Tenochtitlan, founded in 1324, is now known as what city?','Mexico City','Madrid','Costa Rica','Guatemala',3);");
        sqLiteDatabase.execSQL("INSERT INTO " + TABLE_QUESTIONS_AND_ANSWERS+"("+COLUMN_QUESTIONS+","+COLUMN_CORRECT_ANSWER+","+COLUMN_WRONG_ANSWER0+","+COLUMN_WRONG_ANSWER1+","+COLUMN_WRONG_ANSWER2+","+ COLUMN_ID_QUESTIONS+") VALUES('Tenochtitlan, founded in 1324, is now known as what city?','Mexico City','Madrid','Costa Rica','Guatemala',3);");
        sqLiteDatabase.execSQL("INSERT INTO " + TABLE_QUESTIONS_AND_ANSWERS+"("+COLUMN_QUESTIONS+","+COLUMN_CORRECT_ANSWER+","+COLUMN_WRONG_ANSWER0+","+COLUMN_WRONG_ANSWER1+","+COLUMN_WRONG_ANSWER2+","+ COLUMN_ID_QUESTIONS+") VALUES('Tenochtitlan, founded in 1324, is now known as what city?','Mexico City','Madrid','Costa Rica','Guatemala',3);");
        sqLiteDatabase.execSQL("INSERT INTO " + TABLE_QUESTIONS_AND_ANSWERS+"("+COLUMN_QUESTIONS+","+COLUMN_CORRECT_ANSWER+","+COLUMN_WRONG_ANSWER0+","+COLUMN_WRONG_ANSWER1+","+COLUMN_WRONG_ANSWER2+","+ COLUMN_ID_QUESTIONS+") VALUES('Tenochtitlan, founded in 1324, is now known as what city?','Mexico City','Madrid','Costa Rica','Guatemala',3);");
        sqLiteDatabase.execSQL("INSERT INTO " + TABLE_QUESTIONS_AND_ANSWERS+"("+COLUMN_QUESTIONS+","+COLUMN_CORRECT_ANSWER+","+COLUMN_WRONG_ANSWER0+","+COLUMN_WRONG_ANSWER1+","+COLUMN_WRONG_ANSWER2+","+ COLUMN_ID_QUESTIONS+") VALUES('Tenochtitlan, founded in 1324, is now known as what city?','Mexico City','Madrid','Costa Rica','Guatemala',3);");
        sqLiteDatabase.execSQL("INSERT INTO " + TABLE_QUESTIONS_AND_ANSWERS+"("+COLUMN_QUESTIONS+","+COLUMN_CORRECT_ANSWER+","+COLUMN_WRONG_ANSWER0+","+COLUMN_WRONG_ANSWER1+","+COLUMN_WRONG_ANSWER2+","+ COLUMN_ID_QUESTIONS+") VALUES('Tenochtitlan, founded in 1324, is now known as what city?','Mexico City','Madrid','Costa Rica','Guatemala',3);");
        sqLiteDatabase.execSQL("INSERT INTO " + TABLE_QUESTIONS_AND_ANSWERS+"("+COLUMN_QUESTIONS+","+COLUMN_CORRECT_ANSWER+","+COLUMN_WRONG_ANSWER0+","+COLUMN_WRONG_ANSWER1+","+COLUMN_WRONG_ANSWER2+","+ COLUMN_ID_QUESTIONS+") VALUES('Tenochtitlan, founded in 1324, is now known as what city?','Mexico City','Madrid','Costa Rica','Guatemala',3);");
        sqLiteDatabase.execSQL("INSERT INTO " + TABLE_QUESTIONS_AND_ANSWERS+"("+COLUMN_QUESTIONS+","+COLUMN_CORRECT_ANSWER+","+COLUMN_WRONG_ANSWER0+","+COLUMN_WRONG_ANSWER1+","+COLUMN_WRONG_ANSWER2+","+ COLUMN_ID_QUESTIONS+") VALUES('Tenochtitlan, founded in 1324, is now known as what city?','Mexico City','Madrid','Costa Rica','Guatemala',3);");

    }



    //===========================================================================================
    public void listAllQuestionsAndAnswers(SQLiteDatabase sqLiteDatabase){
        Cursor cursor = sqLiteDatabase.rawQuery("SELECT * FROM "+ TABLE_QUESTIONS_AND_ANSWERS + " WHERE " + COLUMN_ID_QUESTIONS,null);

        ArrayList<String> arrQAA = new ArrayList<String>();

        if (cursor.moveToFirst()){
            while (!cursor.isAfterLast()){
                arrQAA.add(cursor.getString(cursor.getColumnIndex(COLUMN_QUESTIONS)));
                cursor.moveToFirst();
            }
        }
    }

    //===========================================================================================
    public void addTables(SQLiteDatabase sqLiteDatabase){
        sqLiteDatabase.execSQL(QUESTIONS_AND_ANSWERS_TABLE_CREATE);
    }


}

